### ISSUE TITLE
Restrict room type access

### ISSUE THREAD

**Issue by SamuelWei** [THM-Health/PILOS#98] opened 2021-01-12 19:35 UTC
**Is your feature request related to a problem? Please describe.**
At the moment all users can use all room types. It is planed to restrict the access to some groups.
The #96 issue adds a server pool to each room type, with this feature the access to the server pools can be limited for some groups.

**Describe the solution you'd like**
Add groups to room types. Users can only create rooms with the room types they have access to.
If user has a room with a room type he has not access to anymore, the start should be prohibited.

**Describe alternatives you've considered**

--

**Additional context**

--

**Comment by dennis95stumm** [comment] 2021-03-04 17:17
Duplicate of #75?

**Comment by SamuelWei** [comment] 2021-03-04 17:21
Not really. This Issue is only one of the future ideas of #75. #75 is about room type presets, that can optionally be enforced, where as this issue restricts the usage of some room types for some groups.

**Closed** 2021-05-21 13:33 UTC
Labels: enhancement
